version: '3'

volumes:
  pgdata:

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "3000:3000"
    links:
      - wdb
      - db
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./scripts/db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=$DJANGO_POSTGRES_PASSWORD

  redis:
    image: redis:6-alpine
    command: redis-server --requirepass $REDIS_PASSWORD
    expose:
      - "6379"

  wdb:
    image: kozea/wdb
    ports:
      - "1984:1984"

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  #   healthcheck:
  #     test: echo | telnet 127.0.0.1 25
