version: '3'

volumes:
  pgdata:

services:
  django:
    build: .
    command: sh scripts/runserver.sh
    volumes:
      - .:/code
      - ./.pdbrc.py:/root/.pdbrc.py
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_SERVICE=${DB_SERVICE}
      - DEBUG=${DEBUG}
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=1
    links:
      - postgres
    depends_on:
      - postgres


  postgres:
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./scripts/db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  wdb:
    image: eduzen/wdb
    expose:
      - 1984

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    healthcheck:
      test: echo | telnet 127.0.0.1 25
