volumes:
  pgdata:
  shell_history:
  ipy_history:
  plausible_db_data:
  plausible_event_data:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET:-development}
    tty: true
    develop:
      # Create a `watch` configuration to update the appl
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /code
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/
        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml
    volumes:
      - .:/code
      - /code/.venv
      - shell_history:/root/hist
      - ipy_history:/root/.ipython/
      - ./secrets/eduzen.json:/root/keys/eduzen.json
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
    environment:
      - BUILD_DATE=$(date +%Y-%m-%d)
      - RELEASE=$(git describe --tags --always --dirty)
    env_file:
      - .env

  db:
    image: postgres:17-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./scripts/db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

  redis:
    image: redis:7-alpine
    expose:
      - "6379"

  plausible:
    image: plausible/analytics:latest
    container_name: plausible
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    ports:
      - "8010:8000"
    depends_on:
      - plausible_db
      - plausible_events_db
    environment:
      - SECRET_KEY_BASE=Cw0pgBXLqnmVnL48KcDgLCgU5dvqI2hHxEPWcUJNtX1PqQ7Vr9kYV4wRTP9mZKRK10LILXuJMvD1Hl7NLPkI9Xu2vCU3
      - ADMIN_USER_EMAIL=me@eduzen.ar
      - ADMIN_USER_PASSWORD=test
      - BASE_URL=http://localhost:8010
      - DATABASE_URL=postgres://postgres:postgres@plausible_db:5432/plausible
      - CLICKHOUSE_DATABASE_URL=http://plausible_events_db:8123/plausible

  plausible_db:
    image: postgres:14-alpine
    container_name: plausible_db
    restart: always
    volumes:
      - plausible_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=plausible

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    container_name: plausible_events_db
    restart: always
    volumes:
      - plausible_event_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_DB=plausible
