version: '3'

volumes:
  pgdata:
  dj-static:

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  www:
    image: nginx:alpine
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=static.eduzen.com.ar
    volumes:
      - dj-static:/usr/share/nginx/html

  django:
    build: .
    command: sh ./scripts/gunicorn_start.sh
    volumes:
      - .:/code
      - dj-static:/code/website/static/
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=${ALLOWED_HOSTS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_SERVICE=${DB_SERVICE}
      - DEBUG=${DEBUG}
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./scripts/db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
