version: '3.9'

volumes:
  pgdata:
  shell_history:
  ipy_history:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
      - shell_history:/root/hist
      - ipy_history:/root/.ipython/
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./scripts/db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=$DJANGO_POSTGRES_PASSWORD

  redis:
    image: redis:6-alpine
    command: redis-server --requirepass $REDIS_PASSWORD
    expose:
      - "6379"

  adminer:
    image: adminer:latest
    profiles: ["debug"]
    restart: always
    ports:
        - 8000:8000
