version: '3.8'

volumes:
  pgdata:

services:
  nginx-proxy:
    restart: always
    image: index.docker.io/jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  media:
    image: nginx:alpine
    restart: always
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=media.eduzen.com.ar
    volumes:
      - ./website/media:/usr/share/nginx/html:ro

  web:
    image: index.docker.io/eduzen/website:latest
    restart: always
    expose:
      - 80
    env_file:
      - .env
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  db:
    image: index.docker.io/postgres:13-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./scripts/db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=${DJANG0_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}

  redis:
    image: index.docker.io/redis:6-alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    expose:
      - "6379"

  watchtower:
    image: index.docker.io/containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/eduzen/.docker/config.json:/config.json:ro
    command: --interval 120
