version: '3.8'

volumes:
  pgdata:

services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # media:
  #   image: nginx:alpine
  #   restart: always
  #   expose:
  #     - "8080"
  #   environment:
  #     - VIRTUAL_HOST=media.eduzen.com.ar
  #   volumes:
  #     - ./website/media:/usr/share/nginx/html:ro

  web:
    image: index.docker.io/eduzen/website:latest
    restart: always
    volumes:
      - .:/code
    expose:
      - 80
    env_file:
      - .env
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./scripts/db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:6-alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    expose:
      - "6379"
