version: "3.9"

volumes:
  pgdata:

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    command:
      # Enables the web UI and tells Traefik to listen to docker
      #  "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=ERROR"
      - "--accesslog"
      # - "--log"
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      # - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  media:
    image: index.docker.io/nginx:alpine
    restart: always
    expose:
      - "80"
    volumes:
      - ./media:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`media.eduzen.ar`)"
      - "traefik.http.services.media.loadbalancer.server.port=80"

  web:
    image: index.docker.io/eduzen/website:latest
    restart: always
    expose:
      - 80
    env_file:
      - "./.env"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`eduzen.ar`) || Host(`eduzen.com.ar`) || Host(`eduardoenriquez.com.ar`)"
    volumes:
      - ./media:/code/media
    environment:
      - VIRTUAL_HOST=eduzen.ar,eduzen.com.ar,eduardoenriquez.com.ar

  db:
    image: index.docker.io/postgres:13-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./dump-2021-02-06.sql:/docker-entrypoint-initdb.d/01.sql:ro
    environment:
      - POSTGRES_USER=${DJANGO_POSTGRES_USER}
      - POSTGRES_DB=${DJANGO_POSTGRES_DB}
      - POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}

  redis:
    restart: always
    image: index.docker.io/redis:latest
    command: redis-server --requirepass $REDIS_PASSWORD
    expose:
      - "6379"

  watchtower:
    restart: always
    image: index.docker.io/containrrr/watchtower
    env_file:
      - .env.watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/eduzen/.docker/config.json:/config.json:ro
    command: --interval 60 --cleanup
