#!/bin/bash

NAME="website"                                  # Name of the application
DJANGODIR=/home/eduzen/eduzen/website             # Django project directory
SOCKFILE=/home/eduzen/eduzen/website/website.sock  # we will communicte using this unix socket
USER=eduzen_website                                        # the user to run as
GROUP=eduzen_website                                     # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
TIMEOUT=120
DJANGO_SETTINGS_MODULE=website.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=website.wsgi                     # WSGI module name
ERROR_LOG=/home/eduzen/eduzen/logs/gunicorn/error.log
LOG=/home/eduzen/eduzen/logs/gunicorn/access.log
BIND=127.0.0.1:9000

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
source /home/eduzen/.virtualenvs/website/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --timeout $TIMEOUT \
  --user=$USER --group=$GROUP \
  --bind=$BIND \
  --log-level=debug \
  --log-file=-
