[tool.pytest.ini_options]
addopts = "--ds=website.settings --dc=Test --pdbcls=IPython.terminal.debugger:Pdb -x"
filterwarnings = [
  "ignore::django.utils.deprecation.RemovedInDjango40Warning"
]

[tool.black]
line-length = 120
safe = true
target-version = ['py38']

[tool.isort]
profile = "black"
include_trailing_comma = true
