[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "website/__about__.py"

[project]
name = "website"
description = 'My django blog Repo: http://eduzen.com.ar'
readme = "README.md"
requires-python = ">=3.11"
version = "1.1.1"
license = "MIT"
authors = [
  { name = "Eduardo Enriquez (eduzen)", email = "eduardo.a.enriquez@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
  "django",
  "django-anymail",
  "django-configurations[cache,database,email,search]",
  "django-crispy-forms",
  "django-ckeditor",
  "django-constance[database]",
  "django-extensions",
  "django-filter",
  "django-healthchecks",
  "django-image-cropping",
  "django-money",
  "django-robots",
  "django-simple-captcha",
  "django-autoslug",
  "djangorestframework",
  "django-storages[dropbox]",
  "easy-thumbnails",
  "gunicorn",
  "gevent",
  "Markdown",
  "psycopg2-binary",
  "pygments",
  "redis",
  "sentry-sdk",
  "requests",
  "whitenoise",
]


[project.optional-dependencies]
dev = [
  "coverage",
  "django-debug-toolbar",
  "ipdb",
  "ipython",
  "mypy",
  "factory-boy",
  "pytest",
  "pytest-cov",
  "pytest-django",
  "pytest-mock",
  "pytest-sugar",
  "pytest-xdist",
  "pytest-recording",
  "types-redis",
  "types-requests",
  "hypothesis",
  "coverage",
  # "wdb",
]


[tool.pytest.ini_options]
addopts = "--ds=website.settings.test --dc=Test --pdbcls=IPython.terminal.debugger:Pdb -xs"
filterwarnings = []

[tool.black]
line-length = 120
safe = true
target-version = ['py311']

[tool.isort]
profile = "black"
include_trailing_comma = true

[tool.ruffus]
line_length = 120

[tool.mypy]
ignore_missing_imports = true
