[tool.pytest.ini_options]
addopts = "--ds=website.settings.test --dc=Test --pdbcls=IPython.terminal.debugger:Pdb -xs"
filterwarnings = [
  "ignore::django.utils.deprecation.RemovedInDjango40Warning"
]

[tool.black]
line-length = 120
safe = true
target-version = ['py38']

[tool.isort]
profile = "black"
include_trailing_comma = true

[tool.poetry]
name = "website"
version = "0.1.2"
description = "eduzen.ar"
authors = ["eduzen <eduardo.a.enriquez@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8.1"
Django = "^3.2.3"
django-configurations = {extras = ["cache", "database", "email", "search"], version = "^2.2"}
django-anymail = "^8.2"
django-ckeditor = "^6.0.0"
django-crispy-forms = "^1.11.2"
django-constance = {extras = ["database"], version = "^2.7.0"}
django-extensions = "^3.1.3"
django-image-cropping = "^1.5.0"
django-robots = "^4.0"
django-redis = "^4.12.1"
django-filter = "^2.4.0"
django-simple-captcha = "^0.5.13"
django-money = "^1.3.1"
django-debug-toolbar = "^3.2"
django-autoslug = "^1.9.8"
djangorestframework = "^3.12.2"
django-storages = {extras = ["dropbox"], version = "^1.10.1"}
psycopg2-binary = "^2.8.6"
ipython = "^7.23.1"
requests = "^2.25.1"
sentry-sdk = "^1.3.1"
pre-commit = "^2.12.1"
Markdown = "^3.3.4"
easy-thumbnails = "^2.7"
whitenoise = "^5.2.0"
gunicorn = "^20.1.0"
gevent = "^21.1.2"
django_healthchecks = "^1.4.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
factory-boy = "^3.1.0"
hypothesis = "^6.22.0"
coverage = "^5.5"
codecov = "^2.1.11"
flake8 = "^3.9.0"
flake8-assertive = "^1.3.0"
flake8-django = "^1.1.1"
flake8-bugbear = "^21.4.3"
flake8-comprehensions = "^3.5.0"
pytest-cov = "^2.12.1"
pytest-django = "^4.4.0"
pytest-mock = "^3.6.1"
pytest-sugar = "^0.9.4"
pytest-xdist = "^2.2.1"
ipdb = "^0.13.6"
wdb = "^3.3.0"
django-debug-toolbar = "^3.2"

[virtualenvs]
create = true
local = true
# in-project = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
