[tool.pytest.ini_options]
addopts = "--ds=website.settings.test --dc=Test --pdbcls=IPython.terminal.debugger:Pdb -xs"
filterwarnings = [
  "ignore::django.utils.deprecation.RemovedInDjango40Warning"
]

[tool.black]
line-length = 120
safe = true
target-version = ['py38']

[tool.isort]
profile = "black"
include_trailing_comma = true

[tool.poetry]
name = "website"
version = "0.1.2"
description = "eduzen.ar"
authors = ["eduzen <eduardo.a.enriquez@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.1.4"
django-configurations = {extras = ["cache", "database", "email", "search"], version = "^2.2"}
django-anymail = "^8.1"
django-ckeditor = "^6.0.0"
django-crispy-forms = "^1.10.0"
django-constance = {extras = ["database"], version = "^2.7.0"}
django-extensions = "^3.1.0"
django-image-cropping = "^1.5.0"
django-robots = "^4.0"
django-redis = "^4.12.1"
whitenoise = "^5.2.0"
psycopg2-binary = "^2.8.6"
djangorestframework = "^3.12.2"
django-storages = {extras = ["dropbox"], version = "^1.10.1"}
ipython = "^7.18.1"
requests = "^2.25.0"
sentry-sdk = "^0.19.4"
pre-commit = "^2.9.3"
Markdown = "^3.3.3"
easy-thumbnails = "^2.7"
django-filter = "^2.4.0"
django-simple-captcha = "^0.5.13"
django-money = "^1.1"
django-debug-toolbar = "^3.1.1"
django-autoslug = "^1.9.8"
gunicorn = "^20.0.4"
gevent = "^20.9.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
factory-boy = "^3.1.0"
hypothesis = "^5.43.3"
coverage = "^5.3"
codecov = "^2.1.10"
flake8 = "^3.8.4"
flake8-assertive = "^1.3.0"
flake8-django = "^1.1.1"
flake8-bugbear = "^20.11.1"
flake8-comprehensions = "^3.3.0"
pytest-cov = "^2.10.1"
pytest-django = "^4.1.0"
pytest-mock = "^3.4.0"
pytest-sugar = "^0.9.4"
pytest-xdist = "^2.1.0"
ipdb = "^0.13.4"
wdb = "^3.3.0"
django-debug-toolbar = "^3.1.1"

[virtualenvs]
create = true
local = true
in-project = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
