[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "website/__about__.py"

[project]
name = "website"
description = 'My django blog Repo: http://eduzen.com.ar'
readme = "README.md"
requires-python = ">=3.11"
version = "2.1.1"
license = "MIT"
authors = [
  { name = "Eduardo Enriquez (eduzen)", email = "eduardo.a.enriquez@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
  "django",
  "django-anymail",
  "django-configurations[cache,database,email,search]",
  "django-crispy-forms<2.0",
  "django-cors-headers",
  "django-ckeditor",
  "django-constance[database]",
  "django-extensions",
  "django-filter",
  "django-healthchecks",
  "django-htmx",
  "django-image-cropping",
  "django-money",
  "django-robots",
  "django-simple-captcha",
  "django-autoslug",
  "djangorestframework",
  "django-storages[dropbox]",
  "django-debug-toolbar",
  "easy-thumbnails",
  "gunicorn",
  "gevent",
  "Markdown",
  "python-decouple",
  "psycopg2-binary",
  "pygments",
  "redis",
  "sentry-sdk",
  "requests",
  "whitenoise",
]

[project.optional-dependencies]
dev = [
  "coverage",
  "ipdb",
  "ipython",
  "mypy",
  "factory-boy",
  "pytest",
  "pytest-cov",
  "pytest-django",
  "pytest-mock",
  "pytest-sugar",
  "pytest-xdist",
  "pytest-recording",
  "types-redis",
  "types-requests",
  "hypothesis",
  "coverage",
  "django-browser-reload",
  # "wdb",
]
types = [
  "types-redis",
  "types-requests",
  "django-stubs[compatible-mypy]",
]

[tool.pytest.ini_options]
addopts = "--ds=website.settings.test --dc=Test --pdbcls=IPython.terminal.debugger:Pdb -xs"
filterwarnings = []

[tool.black]
line-length = 120
safe = true
target-version = ['py311']

[tool.isort]
profile = "black"
include_trailing_comma = true

[tool.ruff]
line-length = 120
exclude = [
  "website/settings/base.py",
  "website/settings/test.py",
]

[tool.mypy]
plugins = [
  "./configurations_mypy_django_plugin.py",
  "mypy_django_plugin.main"
]
ignore_missing_imports = true
exclude = [
  "(build|dist)/*",
  "migrations/*"
]

[tool.django-stubs]
django_settings_module = "website.settings.dev"

[tool.coverage.run]
branch = true
source = ["."]
omit = [
  "website/runner.py",
  "website/__init__.py",
  "website/settings/*",
  "website/wsgi.py",
  "website/asgi.py",
  "*/tests/*",
  "*/venv/*",
  "*/manage.py",
  "*/migrations/*",
  "*/factories.py",
]

[tool.coverage.report]
sort = "Cover"
show_missing = true
skip_covered = true
fail_under = 80
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
