# Generated by Django 3.0.3 on 2020-02-16 12:43
import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("expenses", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency="ARS", max_digits=10),
        )
    ]
