# Generated by Django 5.1.4 on 2025-01-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CacheExplorer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Cache Management",
                "verbose_name_plural": "Cache Management",
            },
        ),
    ]
