# Generated by Django 6.0.1 on 2026-01-26 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fast", "0002_requestprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="requestprofile",
            index=models.Index(fields=["-start_time"], name="reqprofile_start_time_idx"),
        ),
        migrations.AddIndex(
            model_name="requestprofile",
            index=models.Index(fields=["path"], name="reqprofile_path_idx"),
        ),
        migrations.AddIndex(
            model_name="requestprofile",
            index=models.Index(fields=["status_code"], name="reqprofile_status_idx"),
        ),
        migrations.AddIndex(
            model_name="requestprofile",
            index=models.Index(fields=["-start_time", "path"], name="reqprofile_time_path_idx"),
        ),
    ]
