# Generated by Django 3.0.6 on 2020-05-26 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_auto_20200523_1753"),
    ]

    operations = []
