# Generated by Django 1.10.6 on 2017-07-01 17:58
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("blog", "0002_dolarpeso")]

    operations = [
        migrations.AlterModelOptions(
            name="dolarpeso",
            options={"verbose_name": "Cambio dolar", "verbose_name_plural": "Historial pesos/dolar   "},
        )
    ]
