# Generated by Django 3.0.7 on 2020-06-06 10:55

import blog.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20200526_1714"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, storage=blog.custom_storages.MediaPublicStorage(), upload_to="post-img/%Y/%m/%d"
            ),
        ),
    ]
