# Generated by Django 4.2.4 on 2023-08-25 12:29

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_tag_options_alter_tag_slug_alter_tag_word"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="pompadour",
            new_name="summary",
        ),
        migrations.AlterField(
            model_name="post",
            name="summary",
            field=models.CharField(blank=True, max_length=800, verbose_name="summary"),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(null=True, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Body text"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, default=django.utils.timezone.now, verbose_name="slug"),
            preserve_default=False,
        ),
    ]
