# Generated by Django 2.2.7 on 2019-11-12 10:22
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0007_auto_20171210_1543")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pompadour",
            field=models.CharField(blank=True, default="", max_length=800, verbose_name="Resumen para portada"),
            preserve_default=False,
        )
    ]
