# Generated by Django 6.0.1 on 2026-01-26 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_post_suggestions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["-published_date"], name="post_published_date_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["-created_date"], name="post_created_date_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["author"], name="post_author_idx"),
        ),
    ]
