# Generated by Django 3.0.3 on 2020-02-16 12:43
import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blog", "0008_auto_20191112_1022")]

    operations = [
        migrations.AlterField(
            model_name="dolarpeso", name="ask", field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)
        ),
        migrations.AlterField(
            model_name="dolarpeso",
            name="balance",
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="dolarpeso", name="bid", field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)
        ),
        migrations.AlterField(
            model_name="dolarpeso", name="rate", field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)
        ),
    ]
