# Generated by Django 3.0.3 on 2020-02-16 12:43
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("blog", "0008_auto_20191112_1022")]

    operations = []
