# Generated by Django 3.0.6 on 2020-05-16 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_auto_20200516_1231"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomPage",
        ),
    ]
