# Generated by Django 3.0.6 on 2020-05-21 15:46

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_delete_custompage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.DeleteModel(
            name="DolarPeso",
        ),
        migrations.AddField(
            model_name="post",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "260x120",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="cropping",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="word",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("word", "slug")},
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
