# Generated by Django 3.0.6 on 2020-05-21 14:24

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_auto_20200517_2015"),
    ]

    operations = [
        migrations.DeleteModel(name="DolarPeso",),
        migrations.AlterField(
            model_name="post",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "260x120",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="cropping",
            ),
        ),
    ]
