# Generated by Django 1.10.5 on 2017-01-22 19:46
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default=b"Site Name", max_length=255)),
                ("subtitle", models.CharField(default=b"Subtitle Name", max_length=255)),
                ("home", models.URLField(default=b"eduardoenriquez.com.ar", max_length=500)),
                ("url_linkedin", models.URLField(default=b"linkedin", max_length=500)),
                ("url_github", models.URLField(default=b"github", max_length=500)),
                ("url_twitter", models.URLField(default=b"twitter", max_length=500)),
            ],
            options={"verbose_name": "Site Configuration"},
        )
    ]
