# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='tab_title',
            field=models.CharField(default=b'Tab title', max_length=255),
        ),
    ]
