# Generated by Django 1.11 on 2017-05-04 02:18
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("config", "0002_siteconfiguration_tab_title")]

    operations = [
        migrations.CreateModel(
            name="TwitterConfiguration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("consumer_key", models.CharField(default=b"consumer key", max_length=255)),
                ("consumer_secret", models.CharField(default=b"consumer secret", max_length=255)),
                ("access_token", models.CharField(default=b"access token", max_length=255)),
                ("access_token_secret", models.CharField(default=b"access token secret", max_length=255)),
            ],
            options={"verbose_name": "Twitter api Configuration"},
        )
    ]
