# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 01:33
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('config', '0003_twitterconfiguration')]

    operations = [
        migrations.CreateModel(
            name='BioConfiguration',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(default=b'Qui\xc3\xa9n les escribe', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={'verbose_name': 'Bio/About configuration'},
        )
    ]
