# Generated by Django 1.11.4 on 2017-10-01 02:53
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("config", "0005_contactconfiguration")]

    operations = [
        migrations.AlterField(
            model_name="bioconfiguration",
            name="title",
            field=models.CharField(default="Quién les escribe", max_length=255),
        ),
        migrations.AlterField(
            model_name="contactconfiguration", name="title", field=models.CharField(default="Contacto", max_length=255)
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="home",
            field=models.URLField(default="eduardoenriquez.com.ar", max_length=500),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="subtitle",
            field=models.CharField(default="Subtitle Name", max_length=255),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="tab_title",
            field=models.CharField(default="Tab title", max_length=255),
        ),
        migrations.AlterField(
            model_name="siteconfiguration", name="title", field=models.CharField(default="Site Name", max_length=255)
        ),
        migrations.AlterField(
            model_name="siteconfiguration", name="url_github", field=models.URLField(default="github", max_length=500)
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="url_linkedin",
            field=models.URLField(default="linkedin", max_length=500),
        ),
        migrations.AlterField(
            model_name="siteconfiguration", name="url_twitter", field=models.URLField(default="twitter", max_length=500)
        ),
        migrations.AlterField(
            model_name="twitterconfiguration",
            name="access_token",
            field=models.CharField(default="access token", max_length=255),
        ),
        migrations.AlterField(
            model_name="twitterconfiguration",
            name="access_token_secret",
            field=models.CharField(default="access token secret", max_length=255),
        ),
        migrations.AlterField(
            model_name="twitterconfiguration",
            name="consumer_key",
            field=models.CharField(default="consumer key", max_length=255),
        ),
        migrations.AlterField(
            model_name="twitterconfiguration",
            name="consumer_secret",
            field=models.CharField(default="consumer secret", max_length=255),
        ),
    ]
