# Generated by Django 1.10.6 on 2017-12-10 18:43
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("config", "0006_auto_20170930_2353")]

    operations = [
        migrations.AlterField(
            model_name="bioconfiguration",
            name="title",
            field=models.CharField(default=b"Qui\xc3\xa9n les escribe", max_length=255),
        )
    ]
