# Generated by Django 1.11.6 on 2018-02-25 22:23
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("config", "0007_auto_20171210_1543")]

    operations = [
        migrations.AlterField(
            model_name="bioconfiguration",
            name="title",
            field=models.CharField(default="Quién les escribe", max_length=255),
        )
    ]
