# Generated by Django 3.0.3 on 2020-02-16 12:43
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("config", "0009_auto_20191112_1022")]

    operations = [
        migrations.AddField(
            model_name="bioconfiguration",
            name="long",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bioconfiguration",
            name="small",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
