# Generated by Django 3.0.6 on 2020-05-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0011_auto_20200216_1322"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactConfiguration",
        ),
        migrations.DeleteModel(
            name="SiteConfiguration",
        ),
        migrations.DeleteModel(
            name="TwitterConfiguration",
        ),
    ]
