# Generated by Django 3.0.6 on 2020-05-25 17:12

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublicImage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("image", models.FileField(upload_to="public/images/%Y/%m/")),
                (
                    "cropping",
                    image_cropping.fields.ImageRatioField(
                        "image",
                        "260x120",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=False,
                        verbose_name="cropping",
                    ),
                ),
            ],
        ),
    ]
