"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sentry_sdk

from .base import *  # NOQA
from sentry_sdk.integrations.django import DjangoIntegration


DEBUG = False
LOG_LEVEL = os.getenv("LOG_LEVEL", "WARN").upper()
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS").split(",")

STATIC_URL = "https://static.eduzen.com.ar/"
MEDIA_URL = "https://media.eduzen.com.ar/"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASS"),
        "HOST": os.getenv("DB_SERVICE"),
        "PORT": os.getenv("DB_PORT"),
    }
}

INSTALLED_APPS += ( 'storages', )

EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
SERVER_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

ANYMAIL = {
    "MAILGUN_API_KEY": os.environ.get("MAILGUN_API_KEY"),
}

sentry_sdk.init(dsn=os.environ.get("SENTRY_DSN"), integrations=[DjangoIntegration()])

DEFAULT_FILE_STORAGE = 'storages.backends.dropbox.DropBoxStorage'
DROPBOX_OAUTH2_TOKEN = os.getenv("DROPBOX_OAUTH2_TOKEN")
DROPBOX_ROOT_PATH = os.getenv("DROPBOX_ROOT_PATH")
DROPBOX_TIMEOUT = int(os.getenv("DROPBOX_TIMEOUT"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": (
                "[DJANGO] %(levelname)s %(asctime)s %(module)s "
                "%(name)s.%(funcName)s:%(lineno)s: %(message)s"
            )
        },
        'verbose': {
            'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt': "%d/%b/%Y %H:%M:%S",
        },
        'simple': {'format': '%(levelname)s %(message)s'},
    },
    "handlers": {
        "console": {"level": LOG_LEVEL, "class": "logging.StreamHandler", "formatter": "verbose"},
    },
    "loggers": {
        "*": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
        'django': {
            'handlers': ['console'],
            'propagate': False,
            'level': LOG_LEVEL,
        },
    },
}
